plugins {
    id 'java'
    id 'io.freefair.lombok' version '9.5.0'
}

group = 'booking-systeme'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation 'org.hibernate.orm:hibernate-core:6.4.4.Final'

    implementation 'org.postgresql:postgresql:42.7.13'
    implementation 'org.flywaydb:flyway-core:13.5.0'
    implementation 'org.flywaydb:flyway-database-postgresql:13.5.0'
    implementation 'com.zaxxer:HikariCP:5.1.0'

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.22.1'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-hibernate6:2.22.1'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.22.1'

    implementation 'org.slf4j:slf4j-api:2.0.17'
    implementation 'ch.qos.logback:logback-classic:1.6.3'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}