plugins {
    id 'java'
    id 'io.freefair.lombok' version '9.5.0'
}

group = 'booking-systeme'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.hibernate.orm:hibernate-core:7.4.7.Final'
    implementation 'org.postgresql:postgresql:42.7.13'
    implementation 'org.flywaydb:flyway-core:13.5.0'
    implementation 'org.flywaydb:flyway-database-postgresql:13.5.0'
    implementation 'com.zaxxer:HikariCP:5.1.0'


    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}